"""Transitions and Transversions."""

import os

from utils import read_fasta

data = """\
>Rosalind_0042
TAGGAGCCCTCTCTAGCCACGAACGTAATACTTTTTAAGCTCTTCTACAGTCAGTTTATC
TGCGGGTAGCAAACGGGAATAAGCATACCTTTGAGCTGCGAAGCTAGGCGCATCTTGGTT
TATTGCCAACCCGGAGCTTTCAGGCCAAATGTAGATATGAAGCAAACTTGAAAGATTCCG
TTCAAGTGAGAGGTCTCTCTGTATTTTTCAACCGGAATAACGTTCAAAGGATCGTGAGTT
TGAATTATGGAAGCACCTCCTTTCTCTCGATTATTGTGAGCAGACCCTCTCGTTCTGTGA
ACACACTGTGCAGCGGGTCCAGGGCCACGCGGATCAGAAAACCGAATTAAAGCCTTAGGG
TAGGGAGAGAACCCGTAACTTCCCTCCCCGTTTTCGCGAAAGCGGCAAGGCTTGGGTGAC
AAACCACCGGGCACCGCCATACACTGAGTCATCCTAAAGTATTTATTAACACAGGGCCGA
CCCGACTGAACTTTTTCAAGCTCAATGAGGACACTGGGGGTAGCTTGGCTAAGTTGAGAA
GGTTGCACGTCTACAAAACTAAAGCATGCCATCTCGCGTGTCACTACGATACAGGCGTGC
TAGTGTGCGTACGTGGCATCCTACTTTTGTCAAATGTGCCCTTCGGCGCAGTTGCATAAC
CATCTTTGGAAAACCCGAAGATTCTCGTCCCACGTCCGCCGAGGAGTAACCCTTGCGACC
GTCAAACTGAATCCTGTGATTATAGCGTCACGGTAATGCTGGCTCAGGCAAGCAGCAAAA
CTTTCAAAGGCTAAACATCATTGGCGACGACCAGCTGACAGTGCTCTTAGAGCAAATGTC
ACATCAAATGGCCGGATCCGCGTTTAGAACTAACTGCCTTTCGCGTTAATGGAACCGGCC
CGTGTCGTACT
>Rosalind_8282
TTGGTATCCTCCCCGGCCACAAACGGAATATCTTTTGAGCCCTTCCGCAGTTCGTTTATC
CGCACGTGACGAACGGGAGTGAATATGCGTTGAGGCTGCGACGCTGAGCGCATCTCGGTT
TATTATCAACTCGGGACTTTCGTGCACAATGTAGATATAAAGCGAAATTGAAAAACTTTC
TTCAGGTGAGAGGTCTCATTGCATTTTTTAATCGGAGTAATCCTCGAAGGATTGCGATGT
TGAGATATAGAGTAACGTCCTCTCTCGCCACTATTGCGAGCAGACCCTCCCGATCTGGGA
GCAGGTTATGCAACGGGTCCAGCGTTATGCCGACCCGAAAATCCGGTTAAAGCTTTTAGG
CGGTGAGAGGACTGGTGATCACCGTCCCTGTTTTTGCGCAAGCGACGAAGATTGGGCAGC
AAACTACCTGGCACTCCCAGTCACTGAGTCATTTTTAAGGGTTTATTAACGGAGGGCCAG
CCCAACTGAACTTTTTTAAGCTCAATGGTGACACTGGGGTTAGATTGGCTAGGCTGAGAC
GGCCGCGCTGTTACTAAAATAAAATGCGCCATCTCATATTTCACCACAACATAAGCTTGC
TGCCAAGCGTATGCAGTAGCCCACTTATGTCATACGAACCTTCCTACGCAATTGCATAGG
CATTCTTGGAAGAGCCAAAGATTATCGTCCCACGTTTGCCGCAGAATGGCCCGCGCGGTC
GAATAGCTGTATTGCGTGAGCACAGCATAGCGGCAATGAGGATTCGGGCCAGTAAGGAGA
TTTTTGAAGTCTAACTATCTTTAGCAACTTTCGGATGATAGTGCTGTTGGAGCAAATGCC
GCATCGAGCGGCCAGATTATCGTTCAAGATTTAGTGTCTTATATACTGGTGAAACGGGCC
CATGCCATACC
"""

data_path = 'TRANS.txt'
with open(data_path, 'w') as file:
    file.write(data)

fasta = list(read_fasta(data_path))
_, seq1 = fasta[0]
_, seq2 = fasta[1]

counts = {'TI': 0, 'TV': 0}
for sym1, sym2 in zip(seq1, seq2):
    syms = {sym1, sym2}
    if sym1 == sym2:
        continue
    elif syms == {'A', 'G'} or syms == {'C', 'T'}:
        counts['TI'] += 1
    else:
        counts['TV'] += 1

print(counts['TI'] / counts['TV'])

os.remove(data_path)
